server:
    port: 8085
    servlet:
        context-path: /roguelife/api/
spring:
    thymeleaf:
        cache: false
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: https://keycloak.roguedev.local/realms/roguelife/protocol/openid-connect/certs
                    issuer-uri: https://keycloak.roguedev.local/realms/roguelife
    mvc:
        format:
            date: iso
            date-time: iso
            time: HH:mm:ss
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER