server:
  port: 8097
jwt:
  auth:
    converter:
      resource-id: ${spring.application.name}
      principal-attribute: preferred_username
spring:
  application:
    name: roguelife-web
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.roguedev.local/realms/roguelife
      client:
        provider:
          roguelife-web:
            issuer-uri: https://keycloak.roguedev.local/realms/roguelife
            user-name-attribute: ${jwt.auth.converter.principal-attribute}
        registration:
          roguelife-web:
            client-id: roguelife-web
            client-secret: 9KquU3yIINHhozOtSNDcgGZEIBbmaaE7
            scope: openid,profile,email

