server:
  port: 8090
spring:
  security:
    oauth2:
      client:
        registration:
          roguelife-web:
            provider: keycloak
            client-id: roguelife-web
            client-secret: 9KquU3yIINHhozOtSNDcgGZEIBbmaaE7
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: openid,profile
        provider:
          keycloak:
            issuer-uri: https://keycloak.roguedev.local/realms/roguelife
