// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.life.species;

import bw.co.roguesystems.life.genus.GenusRepository;
import org.springframework.stereotype.Repository;

/**
 * @see Species
 */
@Repository("speciesDao")
public class SpeciesDaoImpl
    extends SpeciesDaoBase
{
    
    public SpeciesDaoImpl(
        GenusRepository genusRepository,
        SpeciesRepository speciesRepository
    ) {

        super(
            genusRepository,
            speciesRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toSpeciesVO(
        Species source,
        SpeciesVO target)
    {
        // TODO verify behavior of toSpeciesVO
        super.toSpeciesVO(source, target);
        // WARNING! No conversion for target.genus (can't convert source.getGenus():bw.co.roguesystems.life.genus.Genus to bw.co.roguesystems.life.genus.GenusVO
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeciesVO toSpeciesVO(final Species entity)
    {
        // TODO verify behavior of toSpeciesVO
        return super.toSpeciesVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Species loadSpeciesFromSpeciesVO(SpeciesVO speciesVO)
    {
        // TODO implement loadSpeciesFromSpeciesVO
        throw new UnsupportedOperationException("bw.co.roguesystems.life.species.loadSpeciesFromSpeciesVO(SpeciesVO) not yet implemented.");

        /* A typical implementation looks like this:
        if (speciesVO.getId() == null)
        {
            return  Species.Factory.newInstance();
        }
        else
        {
            return this.load(speciesVO.getId());
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public Species speciesVOToEntity(SpeciesVO speciesVO)
    {
        // TODO verify behavior of speciesVOToEntity
        Species entity = this.loadSpeciesFromSpeciesVO(speciesVO);
        this.speciesVOToEntity(speciesVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void speciesVOToEntity(
        SpeciesVO source,
        Species target,
        boolean copyIfNull)
    {
        // TODO verify behavior of speciesVOToEntity
        super.speciesVOToEntity(source, target, copyIfNull);
    }
}